apiVersion: apps/v1
kind: Deployment
metadata:
  name: adserver
spec:
  selector:
    matchLabels:
      app: adserver
  replicas: 1
  template:
    metadata:
      labels:
        app: adserver
    spec:
      containers:
      - name: adserver
        image: shbhsngh/adserver-image
        ports:
        - containerPort: 3000